version: 2.1



jobs:
  error_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - return 1
      when: on_fail
      - run : echo "this an error"

workflows:
  my_workflow:
    jobs:
      - error_job